// import 'package:get/get_navigation/src/root/internacionalization.dart';
//
// class AppTranslations extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys => {
//     'en': {
//       // home screen
//       'hello': 'Hello',
//       "scan_medication": "Scan Medication",
//       "scan_instruction":
//           "Point your camera at the label to identify your medication.",
//       "scan_button": "Scan",
//       "recently_scanned": "Recently Scanned",
//       "font": "Open Sans",
//       // end here
//       // 2nd  recently screen can be added here
//
//       // end 2nd screen
//       //bottom nav bar can be added here
//       'home': 'Home',
//       'scan': 'Scan',
//       'medications': 'Medications',
//       'settings': 'Settings',
//       // end bottom nav bar
//
//       // scane screen can be added here
//       'camera': 'Camera',
//       'photos': 'Photos',
//
//       // end scane screen
//
//       // medication page can be added here
//       "deleteMedication": "Delete Medication",
//       "areYouSureDelete": "Are you sure you want to delete?",
//       "cancel": "Cancel",
//       "delete": "Delete",
//       // ignore: equal_keys_in_map
//       "medications": "Medications",
//       "searchMedications": "Search Medications",
//       "noMedicationsFound": "No medications found.",
//       "unknownMedication": "Unknown, this medication",
//       "brandName": "Brand Name",
//       "checkInfo": "Check info",
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Settings",
//       "editProfile": "Edit Profile",
//       "languageSelection": "Language Selection",
//       "aboutUs": "About Us",
//       "contactUs": "Contact Us",
//       "logout": "Logout",
//       "changePhoto": "Change photo",
//       "fullName": "Full name",
//       "error": "Error",
//       "nameCannotBeEmpty": "Name cannot be empty",
//       "success": "Success",
//       "profileUpdated": "Profile updated successfully",
//       "failedToUpdateProfile": "Failed to update profile",
//       "saveChanges": "Save changes",
//       "english": "English",
//       "spanish": "Spanish (Español)",
//       "french": "French (Français)",
//       "creole": "Creole",
//       "portugese": "Portuguese",
//       "chinese": "Chinese",
//       "russian": "Russian",
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "No medications found",
//       "genericName": "Generic Name",
//       "viewDetails": "View details",
//       "seeAll": "See All",
//
//       // end recently screen
//       'generic_name': 'Generic Name',
//       'brand_name': 'Brand Name',
//       'manufacturer': 'Manufacturer',
//       'drug_class': 'Drug Class',
//       'uses': 'Uses',
//       'dosage_information': 'Dosage Information',
//       'adults': 'Adults',
//       'children': 'Children',
//       'elderly': 'Elderly',
//       'how_to_take': 'How to Take',
//       'side_effects': 'Side Effects',
//       'common': 'Common',
//       'serious': 'Serious',
//       'warnings': 'Warnings',
//       'storage_instructions': 'Storage Instructions',
//       'interactions': 'Interactions',
//       'add_notes': 'Add notes',
//       'save_note': 'Save Note',
//       'play': 'Play',
//     },
//     'es': {
//       // home screen
//       'hello': 'Hola',
//       "scan_medication": "Escanear medicamento",
//       "scan_instruction":
//           "Apunta tu cámara a la etiqueta para identificar tu medicamento.",
//       "scan_button": "Escanear",
//       "recently_scanned": "Escaneado recientemente",
//       "font": "Open Sans",
//
//       // home end here
//       // 2nd screen can be added here
//       'home': 'Inicio',
//       'scan': 'Escanear',
//       'medications': 'Medicamentos',
//       'settings': 'Configuración',
//       // end 2nd screen
//
//       // scane screen can be added here
//       'camera': 'Cámara',
//       'photos': 'Fotos',
//       // end scane screen
//
//       // medication page can be added here
//       "deleteMedication": "Eliminar Medicamento",
//       "areYouSureDelete": "¿Está seguro de que desea eliminar?",
//       "cancel": "Cancelar",
//       "delete": "Eliminar",
//       "medications": "Medicamentos",
//       "searchMedications": "Buscar Medicamentos",
//       "noMedicationsFound": "No se encontraron medicamentos.",
//       "unknownMedication": "Desconocido, este medicamento",
//       "brandName": "Nombre de la Marca",
//       "checkInfo": "Verificar información",
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Configuración",
//       "editProfile": "Editar perfil",
//       "languageSelection": "Selección de idioma",
//       "aboutUs": "Acerca de nosotros",
//       "contactUs": "Contáctenos",
//       "logout": "Cerrar sesión",
//       "changePhoto": "Cambiar foto",
//       "fullName": "Nombre completo",
//       "error": "Error",
//       "nameCannotBeEmpty": "El nombre no puede estar vacío",
//       "success": "Éxito",
//       "profileUpdated": "Perfil actualizado con éxito",
//       "failedToUpdateProfile": "Error al actualizar el perfil",
//       "saveChanges": "Guardar cambios",
//       "english": "Inglés",
//       "spanish": "Español (Español)",
//       "french": "Francés (Français)",
//       "creole": "Criollo",
//       "portugese": "Portugués",
//       "chinese": "Chino",
//       "russian": "Ruso",
//
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "No se encontraron medicamentos",
//       "genericName": "Nombre genérico",
//       "viewDetails": "Ver detalles",
//       "seeAll": "Ver todo",
//       // end recently screen
//       'generic_name': 'Nombre Genérico',
//       'brand_name': 'Nombre de Marca',
//       'manufacturer': 'Fabricante',
//       'drug_class': 'Clase de Droga',
//       'uses': 'Usos',
//       'dosage_information': 'Información de Dosificación',
//       'adults': 'Adultos',
//       'children': 'Niños',
//       'elderly': 'Ancianos',
//       'how_to_take': 'Cómo Tomar',
//       'side_effects': 'Efectos Secundarios',
//       'common': 'Común',
//       'serious': 'Serio',
//       'warnings': 'Advertencias',
//       'storage_instructions': 'Instrucciones de Almacenamiento',
//       'interactions': 'Interacciones',
//       'add_notes': 'Agregar Notas',
//       'save_note': 'Guardar Nota',
//       'play': 'Reproducir',
//     },
//     'fr': {
//       "hello": "Bonjour",
//       "scan_medication": "Numériser le médicament",
//       "scan_instruction":
//           "Pointez votre caméra sur l'étiquette pour identifier votre médicament.",
//       "scan_button": "Numériser",
//       "recently_scanned": "Récemment numérisé",
//       "font": "Open Sans",
//       // custom translations for 2nd screen can be added here
//       'home': 'Accueil',
//       'scan': 'Scanner',
//       'medications': 'Médicaments',
//       'settings': 'Paramètres',
//       // end 2nd screen
//       // scane screen can be added here
//       'camera': 'Caméra',
//       'photos': 'Photos',
//       // end scane screen
//
//       // medication page can be added here
//       "deleteMedication": "Supprimer le Médicament",
//       "areYouSureDelete": "Êtes-vous sûr de vouloir supprimer ?",
//       "cancel": "Annuler",
//       "delete": "Supprimer",
//       "medications": "Médicaments",
//       "searchMedications": "Rechercher des Médicaments",
//       "noMedicationsFound": "Aucun médicament trouvé.",
//       "unknownMedication": "Inconnu, ce médicament",
//       "brandName": "Nom de la Marque",
//       "checkInfo": "Vérifier les informations",
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Paramètres",
//       "editProfile": "Modifier le profil",
//       "languageSelection": "Sélection de la langue",
//       "aboutUs": "À propos de nous",
//       "contactUs": "Contactez-nous",
//       "logout": "Se déconnecter",
//       "changePhoto": "Changer la photo",
//       "fullName": "Nom complet",
//       "error": "Erreur",
//       "nameCannotBeEmpty": "Le nom ne peut pas être vide",
//       "success": "Succès",
//       "profileUpdated": "Profil mis à jour avec succès",
//       "failedToUpdateProfile": "Échec de la mise à jour du profil",
//       "saveChanges": "Sauvegarder les modifications",
//       "english": "Anglais",
//       "spanish": "Espagnol (Español)",
//       "french": "Français (Français)",
//       "creole": "Créole",
//       "portugese": "Portugais",
//       "chinese": "Chinois",
//       "russian": "Russe",
//
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "Aucun médicament trouvé",
//       "genericName": "Nom générique",
//       "viewDetails": "Voir les détails",
//       "seeAll": "Voir tout",
//       // end recently screen
//       'generic_name': 'Nom Générique',
//       'brand_name': 'Nom de Marque',
//       'manufacturer': 'Fabricant',
//       'drug_class': 'Classe de Médicament',
//       'uses': 'Utilisations',
//       'dosage_information': 'Informations sur la Posologie',
//       'adults': 'Adultes',
//       'children': 'Enfants',
//       'elderly': 'Personnes Âgées',
//       'how_to_take': 'Comment Prendre',
//       'side_effects': 'Effets Secondaires',
//       'common': 'Commun',
//       'serious': 'Grave',
//       'warnings': 'Avertissements',
//       'storage_instructions': 'Instructions de Stockage',
//       'interactions': 'Interactions',
//       'add_notes': 'Ajouter des Notes',
//       'save_note': 'Enregistrer la Note',
//       'play': 'Jouer',
//     },
//     'pt': {
//       "hello": "Olá",
//       "scan_medication": "Escanear medicamento",
//       "scan_instruction":
//           "Aponte sua câmera para o rótulo para identificar o seu medicamento.",
//       "scan_button": "Escanear",
//       "recently_scanned": "Escaneado recentemente",
//       "font": "Open Sans",
//       // 2nd screen can be added here
//
//       // end 2nd screen
//       // custom translations for bottom nav bar
//       'home': 'Início',
//       'scan': 'Escanear',
//       'medications': 'Medicamentos',
//       'settings': 'Configurações',
//       // end bottom nav bar
//       // scane screen can be added here
//       'camera': 'Câmera',
//       'photos': 'Fotos',
//       // end scane screen
//
//       // medication page can be added here
//       "deleteMedication": "Excluir Medicamento",
//       "areYouSureDelete": "Tem certeza de que deseja excluir?",
//       "cancel": "Cancelar",
//       "delete": "Excluir",
//       "medications": "Medicamentos",
//       "searchMedications": "Buscar Medicamentos",
//       "noMedicationsFound": "Nenhum medicamento encontrado.",
//       "unknownMedication": "Desconhecido, este medicamento",
//       "brandName": "Nome da Marca",
//       "checkInfo": "Verificar informações",
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Configurações",
//       "editProfile": "Editar perfil",
//       "languageSelection": "Seleção de idioma",
//       "aboutUs": "Sobre nós",
//       "contactUs": "Contate-nos",
//       "logout": "Sair",
//       "changePhoto": "Mudar foto",
//       "fullName": "Nome completo",
//       "error": "Erro",
//       "nameCannotBeEmpty": "O nome não pode estar vazio",
//       "success": "Sucesso",
//       "profileUpdated": "Perfil atualizado com sucesso",
//       "failedToUpdateProfile": "Falha ao atualizar o perfil",
//       "saveChanges": "Salvar alterações",
//       "english": "Inglês",
//       "spanish": "Espanhol (Español)",
//       "french": "Francês (Français)",
//       "creole": "Criolo",
//       "portugese": "Português",
//       "chinese": "Chinês",
//       "russian": "Russo",
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "Nenhum medicamento encontrado",
//       "genericName": "Nome genérico",
//       "viewDetails": "Ver detalhes",
//       "seeAll": "Ver tudo",
//
//       // end recently screen
//       'generic_name': 'Nome Genérico',
//       'brand_name': 'Nome da Marca',
//       'manufacturer': 'Fabricante',
//       'drug_class': 'Classe de Droga',
//       'uses': 'Usos',
//       'dosage_information': 'Informação de Dosagem',
//       'adults': 'Adultos',
//       'children': 'Crianças',
//       'elderly': 'Idosos',
//       'how_to_take': 'Como Tomar',
//       'side_effects': 'Efeitos Colaterais',
//       'common': 'Comum',
//       'serious': 'Sério',
//       'warnings': 'Avisos',
//       'storage_instructions': 'Instruções de Armazenamento',
//       'interactions': 'Interações',
//       'add_notes': 'Adicionar Notas',
//       'save_note': 'Salvar Nota',
//       'play': 'Tocar',
//     },
//     'ht': {
//       "hello": "Bonjou",
//       "scan_medication": "Eskane medikaman",
//       "scan_instruction":
//           "Pwen kamera ou sou etikèt la pou idantifye medikaman ou.",
//       "scan_button": "Eskane",
//       "recently_scanned": "Eskane dènyèman",
//       "font": "Open Sans",
//       // 2nd screen can be added here
//
//       // end 2nd screen
//       // custom translations for bottom nav bar
//       'home': 'Lakay',
//       'scan': 'Eskane',
//       'medications': 'Medikaman',
//       'settings': 'Paramèt',
//       // end bottom nav bar
//       // scane screen can be added here
//       'camera': 'Kamera',
//       'photos': 'Foto',
//       // end scane screen
//       // medication page can be added here
//       "deleteMedication": "Efase Medikaman",
//       "areYouSureDelete": "Eske ou sèten ou vle efase?",
//       "cancel": "Anile",
//       "delete": "Efase",
//       "medications": "Medikaman",
//       "searchMedications": "Rechèch Medikaman",
//       "noMedicationsFound": "Pataje pa jwenn okenn medikaman.",
//       "unknownMedication": "Enkonu, sa a medikaman",
//       "brandName": "Non Mak",
//       "checkInfo": "Tcheke enfòmasyon",
//
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Anviwònman",
//       "editProfile": "Modifye pwofil",
//       "languageSelection": "Seleksyon lang",
//       "aboutUs": "Sou nou",
//       "contactUs": "Kontakte nou",
//       "logout": "Dekonekte",
//       "changePhoto": "Chanje foto",
//       "fullName": "Non konplè",
//       "error": "Erè",
//       "nameCannotBeEmpty": "Non pa ka vid",
//       "success": "Siksè",
//       "profileUpdated": "Pwofil mete ajou avèk siksè",
//       "failedToUpdateProfile": "Echwe mete ajou pwofil la",
//       "saveChanges": "Sove chanjman yo",
//       "english": "Angle",
//       "spanish": "Panyòl (Español)",
//       "french": "Franse (Français)",
//       "creole": "Kreyòl",
//       "portugese": "Pòtigè",
//       "chinese": "Chinwa",
//       "russian": "Ris",
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "Pa gen medikaman jwenn",
//       "genericName": "Non jeneral",
//       "viewDetails": "Gade detay",
//       "seeAll": "Gade tout",
//       // end recently screen
//       'generic_name': 'Non Jenerik',
//       'brand_name': 'Non Mak',
//       'manufacturer': 'Manifakti',
//       'drug_class': 'Klas Dwòg',
//       'uses': 'Itilizasyon',
//       'dosage_information': 'Enfòmasyon sou Dozaj',
//       'adults': 'Granmoun',
//       'children': 'Timoun',
//       'elderly': 'Granmoun Aje',
//       'how_to_take': 'Kijan pou Pran',
//       'side_effects': 'Efè Segondè',
//       'common': 'Komen',
//       'serious': 'Grav',
//       'warnings': 'Avètisman',
//       'storage_instructions': 'Enstriksyon pou Estoke',
//       'interactions': 'Entèraksyon',
//       'add_notes': 'Ajoute Nòt',
//       'save_note': 'Anrejistre Nòt',
//       'play': 'Jwe',
//     },
//     'ru': {
//       "hello": "Здравствуйте",
//       "scan_medication": "Сканировать медикамент",
//       "scan_instruction":
//           "Направьте камеру на этикетку, чтобы определить ваше лекарство.",
//       "scan_button": "Сканировать",
//       "recently_scanned": "Недавнее сканирование",
//       "font": "Open Sans",
//       // 2nd screen can be added here
//
//       // end 2nd screen
//       // custom translations for bottom nav bar
//       'home': 'Главная',
//       'scan': 'Сканировать',
//       'medications': 'Лекарства',
//       'settings': 'Настройки',
//       // end bottom nav bar
//       // scane screen can be added here
//       'camera': 'Камера',
//       'photos': 'Фотографии',
//       // end scane screen
//       // medication page can be added here
//       "deleteMedication": "Удалить лекарство",
//       "areYouSureDelete": "Вы уверены, что хотите удалить?",
//       "cancel": "Отменить",
//       "delete": "Удалить",
//       "medications": "Лекарства",
//       "searchMedications": "Поиск лекарств",
//       "noMedicationsFound": "Лекарства не найдены.",
//       "unknownMedication": "Неизвестно, это лекарство",
//       "brandName": "Марка",
//       "checkInfo": "Проверить информацию",
//       // end medication page
//
//       // setting page can be added here
//       "settings": "Настройки",
//       "editProfile": "Редактировать профиль",
//       "languageSelection": "Выбор языка",
//       "aboutUs": "О нас",
//       "contactUs": "Свяжитесь с нами",
//       "logout": "Выйти",
//       "changePhoto": "Изменить фото",
//       "fullName": "Полное имя",
//       "error": "Ошибка",
//       "nameCannotBeEmpty": "Имя не может быть пустым",
//       "success": "Успех",
//       "profileUpdated": "Профиль успешно обновлен",
//       "failedToUpdateProfile": "Не удалось обновить профиль",
//       "saveChanges": "Сохранить изменения",
//       "english": "Английский",
//       "spanish": "Испанский (Español)",
//       "french": "Французский (Français)",
//       "creole": "Креольский",
//       "portugese": "Португальский",
//       "chinese": "Китайский",
//       "russian": "Русский",
//       // end setting page
//
//       // recently screen can be added here
//       "noMedicationsFound": "Медикаменты не найдены",
//       "genericName": "Общее название",
//       "viewDetails": "Посмотреть детали",
//       "seeAll": "Посмотреть все",
//       // end recently screen
//       'generic_name': 'Общее Название',
//       'brand_name': 'Торговая Марка',
//       'manufacturer': 'Производитель',
//       'drug_class': 'Класс Препарата',
//       'uses': 'Применение',
//       'dosage_information': 'Информация о Дозировке',
//       'adults': 'Взрослые',
//       'children': 'Дети',
//       'elderly': 'Пожилые',
//       'how_to_take': 'Как Принимать',
//       'side_effects': 'Побочные Эффекты',
//       'common': 'Обычные',
//       'serious': 'Серьёзные',
//       'warnings': 'Предупреждения',
//       'storage_instructions': 'Инструкции по Хранению',
//       'interactions': 'Взаимодействия',
//       'add_notes': 'Добавить Заметки',
//       'save_note': 'Сохранить Заметку',
//       'play': 'Воспроизвести',
//     },
//     'zh_Hans_CN': {
//       "hello": "你好",
//       "scan_medication": "扫描药物",
//       "scan_instruction": "将您的摄像头对准标签以识别药物。",
//       "scan_button": "扫描",
//       "recently_scanned": "最近扫描",
//       "font": "Open Sans",
//       'home': '首页',
//       'scan': '扫描',
//       'medications': '药物',
//       'settings': '设置',
//       'camera': '相机',
//       'photos': '照片',
//       "deleteMedication": "删除药物",
//       "areYouSureDelete": "您确定要删除吗？",
//       "cancel": "取消",
//       "delete": "删除",
//       "searchMedications": "搜索药物",
//       "noMedicationsFound": "未找到药物。",
//       "unknownMedication": "未知，此药物",
//       "brand_name": "品牌名称",
//       "checkInfo": "检查信息",
//       "editProfile": "编辑个人资料",
//       "languageSelection": "语言选择",
//       "aboutUs": "关于我们",
//       "contactUs": "联系我们",
//       "logout": "退出",
//       "changePhoto": "更改照片",
//       "fullName": "全名",
//       "error": "错误",
//       "nameCannotBeEmpty": "姓名不能为空",
//       "success": "成功",
//       "profileUpdated": "个人资料更新成功",
//       "failedToUpdateProfile": "更新个人资料失败",
//       "saveChanges": "保存更改",
//       "english": "英语",
//       "spanish": "西班牙语 (Español)",
//       "french": "法语 (Français)",
//       "creole": "克里奥尔语",
//       "portugese": "葡萄牙语",
//       "chinese": "中文",
//       "russian": "俄语",
//       "genericName": "通用名称",
//       "viewDetails": "查看详情",
//       "seeAll": "查看全部",
//       'generic_name': '通用名称',
//       'manufacturer': '制造商',
//       'drug_class': '药物类别',
//       'uses': '用途',
//       'dosage_information': '剂量信息',
//       'adults': '成人',
//       'children': '儿童',
//       'elderly': '老年人',
//       'how_to_take': '如何服用',
//       'side_effects': '副作用',
//       'common': '常见',
//       'serious': '严重',
//       'warnings': '警告',
//       'storage_instructions': '存储说明',
//       'interactions': '相互作用',
//       'add_notes': '添加备注',
//       'save_note': '保存备注',
//       'play': '播放',
//     },
//     // ✅ Also add simpler fallback keys
//     'zh_CN': {
//       "hello": "你好",
//       "scan_medication": "扫描药物",
//       "scan_instruction": "将您的摄像头对准标签以识别药物。",
//       "scan_button": "扫描",
//       "recently_scanned": "最近扫描",
//       "font": "Open Sans",
//       'home': '首页',
//       'scan': '扫描',
//       'medications': '药物',
//       'settings': '设置',
//       'camera': '相机',
//       'photos': '照片',
//       "deleteMedication": "删除药物",
//       "areYouSureDelete": "您确定要删除吗？",
//       "cancel": "取消",
//       "delete": "删除",
//       "searchMedications": "搜索药物",
//       "noMedicationsFound": "未找到药物。",
//       "unknownMedication": "未知，此药物",
//       "brand_name": "品牌名称",
//       "checkInfo": "检查信息",
//       "editProfile": "编辑个人资料",
//       "languageSelection": "语言选择",
//       "aboutUs": "关于我们",
//       "contactUs": "联系我们",
//       "logout": "退出",
//       "changePhoto": "更改照片",
//       "fullName": "全名",
//       "error": "错误",
//       "nameCannotBeEmpty": "姓名不能为空",
//       "success": "成功",
//       "profileUpdated": "个人资料更新成功",
//       "failedToUpdateProfile": "更新个人资料失败",
//       "saveChanges": "保存更改",
//       "english": "英语",
//       "spanish": "西班牙语 (Español)",
//       "french": "法语 (Français)",
//       "creole": "克里奥尔语",
//       "portugese": "葡萄牙语",
//       "chinese": "中文",
//       "russian": "俄语",
//       "genericName": "通用名称",
//       "viewDetails": "查看详情",
//       "seeAll": "查看全部",
//       'generic_name': '通用名称',
//       'manufacturer': '制造商',
//       'drug_class': '药物类别',
//       'uses': '用途',
//       'dosage_information': '剂量信息',
//       'adults': '成人',
//       'children': '儿童',
//       'elderly': '老年人',
//       'how_to_take': '如何服用',
//       'side_effects': '副作用',
//       'common': '常见',
//       'serious': '严重',
//       'warnings': '警告',
//       'storage_instructions': '存储说明',
//       'interactions': '相互作用',
//       'add_notes': '添加备注',
//       'save_note': '保存备注',
//       'play': '播放',
//     },
//     'zh': {
//       // Simplest fallback
//       "hello": "你好",
//       "scan_medication": "扫描药物",
//       "scan_instruction": "将您的摄像头对准标签以识别药物。",
//       "scan_button": "扫描",
//       "recently_scanned": "最近扫描",
//       'home': '首页',
//       'scan': '扫描',
//       'medications': '药物',
//       'settings': '设置',
//       'play': '播放',
//     },
//   };
// }





import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // ============ HOME SCREEN ============
      'hello': 'Hello',
      'scan_medication': 'Scan Medication',
      'scan_instruction': 'Point your camera at the label to identify your medication.',
      'scan_button': 'Scan',
      'recently_scanned': 'Recently Scanned',
      'font': 'Open Sans',
      'no_medications_found': 'No medications found',
      'generic_name': 'Generic Name',
      'view_details': 'View details',
      'see_all': 'See All',

      // ============ BOTTOM NAV ============
      'home': 'Home',
      'scan': 'Scan',
      'medications': 'Medications',
      'settings': 'Settings',

      // ============ SCAN SCREEN ============
      'camera': 'Camera',
      'photos': 'Photos',
      'please_select_an_image_first': 'Please select an image first',
      'please_login_to_continue': 'Please login to continue',
      'uploading_image': 'Uploading image...',
      'ai_is_analyzing_the_image': 'AI is analyzing the image...',
      'processing_medication_data': 'Processing medication data...',
      'this_may_take_a_few_seconds': 'This may take a few seconds',
      'please_do_not_close_the_app': 'Please do not close the app',
      'session_expired_please_login_again': 'Session expired. Please login again.',
      'invalid_image_or_format_not_supported': 'Invalid image or format not supported',
      'server_error_please_try_again_later': 'Server error. Please try again later.',
      'no_internet_connection': 'No internet connection. Please check your network.',
      'request_timed_out_please_try_again': 'Request timed out. Please try again.',
      'something_went_wrong_please_try_again': 'Something went wrong. Please try again.',
      'analyzing_image': 'Analyzing image...',
      'processing': 'Processing...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Delete Medication',
      'are_you_sure_delete': 'Are you sure you want to delete?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'search_medications': 'Search Medications',
      'unknown_medication': 'Unknown, this medication',
      'brand_name': 'Brand Name',
      'check_info': 'Check info',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Edit Profile',
      'language_selection': 'Language Selection',
      'about_us': 'About Us',
      'contact_us': 'Contact Us',
      'logout': 'Logout',
      'change_photo': 'Change photo',
      'full_name': 'Full name',
      'error': 'Error',
      'name_cannot_be_empty': 'Name cannot be empty',
      'success': 'Success',
      'profile_updated': 'Profile updated successfully',
      'failed_to_update_profile': 'Failed to update profile',
      'save_changes': 'Save changes',
      'english': 'English',
      'spanish': 'Spanish (Español)',
      'french': 'French (Français)',
      'creole': 'Creole',
      'portugese': 'Portuguese',
      'chinese': 'Chinese',
      'russian': 'Russian',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Manufacturer',
      'drug_class': 'Drug Class',
      'uses': 'Uses',
      'dosage_information': 'Dosage Information',
      'adults': 'Adults',
      'children': 'Children',
      'elderly': 'Elderly',
      'how_to_take': 'How to Take',
      'side_effects': 'Side Effects',
      'common': 'Common',
      'serious': 'Serious',
      'warnings': 'Warnings',
      'storage_instructions': 'Storage Instructions',
      'interactions': 'Interactions',
      'add_notes': 'Add notes',
      'save_note': 'Save Note',
      'play': 'Play',
      'pause': 'Pause',
      'no_medication_data': 'No medication data',
    },

    'es': {
      // ============ HOME SCREEN ============
      'hello': 'Hola',
      'scan_medication': 'Escanear medicamento',
      'scan_instruction': 'Apunta tu cámara a la etiqueta para identificar tu medicamento.',
      'scan_button': 'Escanear',
      'recently_scanned': 'Escaneado recientemente',
      'font': 'Open Sans',
      'no_medications_found': 'No se encontraron medicamentos',
      'generic_name': 'Nombre genérico',
      'view_details': 'Ver detalles',
      'see_all': 'Ver todo',

      // ============ BOTTOM NAV ============
      'home': 'Inicio',
      'scan': 'Escanear',
      'medications': 'Medicamentos',
      'settings': 'Configuración',

      // ============ SCAN SCREEN ============
      'camera': 'Cámara',
      'photos': 'Fotos',
      'please_select_an_image_first': 'Por favor, selecciona una imagen primero',
      'please_login_to_continue': 'Por favor, inicia sesión para continuar',
      'uploading_image': 'Subiendo imagen...',
      'ai_is_analyzing_the_image': 'La IA está analizando la imagen...',
      'processing_medication_data': 'Procesando datos del medicamento...',
      'this_may_take_a_few_seconds': 'Esto puede tomar unos segundos',
      'please_do_not_close_the_app': 'Por favor, no cierres la aplicación',
      'session_expired_please_login_again': 'Sesión expirada. Por favor, inicia sesión nuevamente.',
      'invalid_image_or_format_not_supported': 'Imagen inválida o formato no soportado',
      'server_error_please_try_again_later': 'Error del servidor. Por favor, intenta más tarde.',
      'no_internet_connection': 'Sin conexión a internet. Por favor, revisa tu red.',
      'request_timed_out_please_try_again': 'Tiempo de espera agotado. Por favor, intenta nuevamente.',
      'something_went_wrong_please_try_again': 'Algo salió mal. Por favor, intenta nuevamente.',
      'analyzing_image': 'Analizando imagen...',
      'processing': 'Procesando...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Eliminar Medicamento',
      'are_you_sure_delete': '¿Está seguro de que desea eliminar?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'search_medications': 'Buscar Medicamentos',
      'unknown_medication': 'Desconocido, este medicamento',
      'brand_name': 'Nombre de la Marca',
      'check_info': 'Verificar información',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Editar perfil',
      'language_selection': 'Selección de idioma',
      'about_us': 'Acerca de nosotros',
      'contact_us': 'Contáctenos',
      'logout': 'Cerrar sesión',
      'change_photo': 'Cambiar foto',
      'full_name': 'Nombre completo',
      'error': 'Error',
      'name_cannot_be_empty': 'El nombre no puede estar vacío',
      'success': 'Éxito',
      'profile_updated': 'Perfil actualizado con éxito',
      'failed_to_update_profile': 'Error al actualizar el perfil',
      'save_changes': 'Guardar cambios',
      'english': 'Inglés',
      'spanish': 'Español',
      'french': 'Francés',
      'creole': 'Criollo',
      'portugese': 'Portugués',
      'chinese': 'Chino',
      'russian': 'Ruso',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Fabricante',
      'drug_class': 'Clase de Droga',
      'uses': 'Usos',
      'dosage_information': 'Información de Dosificación',
      'adults': 'Adultos',
      'children': 'Niños',
      'elderly': 'Ancianos',
      'how_to_take': 'Cómo Tomar',
      'side_effects': 'Efectos Secundarios',
      'common': 'Común',
      'serious': 'Serio',
      'warnings': 'Advertencias',
      'storage_instructions': 'Instrucciones de Almacenamiento',
      'interactions': 'Interacciones',
      'add_notes': 'Agregar Notas',
      'save_note': 'Guardar Nota',
      'play': 'Reproducir',
      'pause': 'Pausa',
      'no_medication_data': 'Sin datos del medicamento',
    },

    'fr': {
      // ============ HOME SCREEN ============
      'hello': 'Bonjour',
      'scan_medication': 'Numériser le médicament',
      'scan_instruction': 'Pointez votre caméra sur l\'étiquette pour identifier votre médicament.',
      'scan_button': 'Numériser',
      'recently_scanned': 'Récemment numérisé',
      'font': 'Open Sans',
      'no_medications_found': 'Aucun médicament trouvé',
      'generic_name': 'Nom générique',
      'view_details': 'Voir les détails',
      'see_all': 'Voir tout',

      // ============ BOTTOM NAV ============
      'home': 'Accueil',
      'scan': 'Scanner',
      'medications': 'Médicaments',
      'settings': 'Paramètres',

      // ============ SCAN SCREEN ============
      'camera': 'Caméra',
      'photos': 'Photos',
      'please_select_an_image_first': 'Veuillez d\'abord sélectionner une image',
      'please_login_to_continue': 'Veuillez vous connecter pour continuer',
      'uploading_image': 'Téléchargement de l\'image...',
      'ai_is_analyzing_the_image': 'L\'IA analyse l\'image...',
      'processing_medication_data': 'Traitement des données du médicament...',
      'this_may_take_a_few_seconds': 'Cela peut prendre quelques secondes',
      'please_do_not_close_the_app': 'Veuillez ne pas fermer l\'application',
      'session_expired_please_login_again': 'Session expirée. Veuillez vous reconnecter.',
      'invalid_image_or_format_not_supported': 'Image invalide ou format non supporté',
      'server_error_please_try_again_later': 'Erreur du serveur. Veuillez réessayer plus tard.',
      'no_internet_connection': 'Pas de connexion internet. Veuillez vérifier votre réseau.',
      'request_timed_out_please_try_again': 'Délai d\'attente dépassé. Veuillez réessayer.',
      'something_went_wrong_please_try_again': 'Quelque chose s\'est mal passé. Veuillez réessayer.',
      'analyzing_image': 'Analyse de l\'image...',
      'processing': 'Traitement en cours...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Supprimer le Médicament',
      'are_you_sure_delete': 'Êtes-vous sûr de vouloir supprimer ?',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'search_medications': 'Rechercher des Médicaments',
      'unknown_medication': 'Inconnu, ce médicament',
      'brand_name': 'Nom de la Marque',
      'check_info': 'Vérifier les informations',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Modifier le profil',
      'language_selection': 'Sélection de la langue',
      'about_us': 'À propos de nous',
      'contact_us': 'Contactez-nous',
      'logout': 'Se déconnecter',
      'change_photo': 'Changer la photo',
      'full_name': 'Nom complet',
      'error': 'Erreur',
      'name_cannot_be_empty': 'Le nom ne peut pas être vide',
      'success': 'Succès',
      'profile_updated': 'Profil mis à jour avec succès',
      'failed_to_update_profile': 'Échec de la mise à jour du profil',
      'save_changes': 'Sauvegarder les modifications',
      'english': 'Anglais',
      'spanish': 'Espagnol',
      'french': 'Français',
      'creole': 'Créole',
      'portugese': 'Portugais',
      'chinese': 'Chinois',
      'russian': 'Russe',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Fabricant',
      'drug_class': 'Classe de Médicament',
      'uses': 'Utilisations',
      'dosage_information': 'Informations sur la Posologie',
      'adults': 'Adultes',
      'children': 'Enfants',
      'elderly': 'Personnes Âgées',
      'how_to_take': 'Comment Prendre',
      'side_effects': 'Effets Secondaires',
      'common': 'Commun',
      'serious': 'Grave',
      'warnings': 'Avertissements',
      'storage_instructions': 'Instructions de Stockage',
      'interactions': 'Interactions',
      'add_notes': 'Ajouter des Notes',
      'save_note': 'Enregistrer la Note',
      'play': 'Jouer',
      'pause': 'Pause',
      'no_medication_data': 'Aucune donnée de médicament',
    },

    'pt': {
      // ============ HOME SCREEN ============
      'hello': 'Olá',
      'scan_medication': 'Escanear medicamento',
      'scan_instruction': 'Aponte sua câmera para o rótulo para identificar o seu medicamento.',
      'scan_button': 'Escanear',
      'recently_scanned': 'Escaneado recentemente',
      'font': 'Open Sans',
      'no_medications_found': 'Nenhum medicamento encontrado',
      'generic_name': 'Nome genérico',
      'view_details': 'Ver detalhes',
      'see_all': 'Ver tudo',

      // ============ BOTTOM NAV ============
      'home': 'Início',
      'scan': 'Escanear',
      'medications': 'Medicamentos',
      'settings': 'Configurações',

      // ============ SCAN SCREEN ============
      'camera': 'Câmera',
      'photos': 'Fotos',
      'please_select_an_image_first': 'Por favor, selecione uma imagem primeiro',
      'please_login_to_continue': 'Por favor, faça login para continuar',
      'uploading_image': 'Carregando imagem...',
      'ai_is_analyzing_the_image': 'IA está analisando a imagem...',
      'processing_medication_data': 'Processando dados do medicamento...',
      'this_may_take_a_few_seconds': 'Isso pode levar alguns segundos',
      'please_do_not_close_the_app': 'Por favor, não feche o aplicativo',
      'session_expired_please_login_again': 'Sessão expirada. Por favor, faça login novamente.',
      'invalid_image_or_format_not_supported': 'Imagem inválida ou formato não suportado',
      'server_error_please_try_again_later': 'Erro no servidor. Por favor, tente mais tarde.',
      'no_internet_connection': 'Sem conexão com a internet. Verifique sua rede.',
      'request_timed_out_please_try_again': 'Tempo limite excedido. Por favor, tente novamente.',
      'something_went_wrong_please_try_again': 'Algo deu errado. Por favor, tente novamente.',
      'analyzing_image': 'Analisando imagem...',
      'processing': 'Processando...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Excluir Medicamento',
      'are_you_sure_delete': 'Tem certeza de que deseja excluir?',
      'cancel': 'Cancelar',
      'delete': 'Excluir',
      'search_medications': 'Buscar Medicamentos',
      'unknown_medication': 'Desconhecido, este medicamento',
      'brand_name': 'Nome da Marca',
      'check_info': 'Verificar informações',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Editar perfil',
      'language_selection': 'Seleção de idioma',
      'about_us': 'Sobre nós',
      'contact_us': 'Contate-nos',
      'logout': 'Sair',
      'change_photo': 'Mudar foto',
      'full_name': 'Nome completo',
      'error': 'Erro',
      'name_cannot_be_empty': 'O nome não pode estar vazio',
      'success': 'Sucesso',
      'profile_updated': 'Perfil atualizado com sucesso',
      'failed_to_update_profile': 'Falha ao atualizar o perfil',
      'save_changes': 'Salvar alterações',
      'english': 'Inglês',
      'spanish': 'Espanhol',
      'french': 'Francês',
      'creole': 'Criolo',
      'portugese': 'Português',
      'chinese': 'Chinês',
      'russian': 'Russo',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Fabricante',
      'drug_class': 'Classe de Droga',
      'uses': 'Usos',
      'dosage_information': 'Informação de Dosagem',
      'adults': 'Adultos',
      'children': 'Crianças',
      'elderly': 'Idosos',
      'how_to_take': 'Como Tomar',
      'side_effects': 'Efeitos Colaterais',
      'common': 'Comum',
      'serious': 'Sério',
      'warnings': 'Avisos',
      'storage_instructions': 'Instruções de Armazenamento',
      'interactions': 'Interações',
      'add_notes': 'Adicionar Notas',
      'save_note': 'Salvar Nota',
      'play': 'Tocar',
      'pause': 'Pausa',
      'no_medication_data': 'Sem dados do medicamento',
    },

    'ht': {
      // ============ HOME SCREEN ============
      'hello': 'Bonjou',
      'scan_medication': 'Eskane medikaman',
      'scan_instruction': 'Pwen kamera ou sou etikèt la pou idantifye medikaman ou.',
      'scan_button': 'Eskane',
      'recently_scanned': 'Eskane dènyèman',
      'font': 'Open Sans',
      'no_medications_found': 'Pa gen medikaman jwenn',
      'generic_name': 'Non jeneral',
      'view_details': 'Gade detay',
      'see_all': 'Gade tout',

      // ============ BOTTOM NAV ============
      'home': 'Lakay',
      'scan': 'Eskane',
      'medications': 'Medikaman',
      'settings': 'Paramèt',

      // ============ SCAN SCREEN ============
      'camera': 'Kamera',
      'photos': 'Foto',
      'please_select_an_image_first': 'Tanpri chwazi yon imaj an premye',
      'please_login_to_continue': 'Tanpri konekte pou kontinye',
      'uploading_image': 'Chaje imaj...',
      'ai_is_analyzing_the_image': 'IA ap analize imaj la...',
      'processing_medication_data': 'Tretman done medikaman...',
      'this_may_take_a_few_seconds': 'Sa ka pran kèk segonn',
      'please_do_not_close_the_app': 'Tanpri pa fèmen aplikasyon an',
      'session_expired_please_login_again': 'Sesyon ekspire. Tanpri konekte ankò.',
      'invalid_image_or_format_not_supported': 'Imaj pa valab oswa foma pa sipòte',
      'server_error_please_try_again_later': 'Erè sèvè. Tanpri eseye ankò pita.',
      'no_internet_connection': 'Pa gen koneksyon entènèt. Tanpri tcheke rezo ou.',
      'request_timed_out_please_try_again': 'Tan depase. Tanpri eseye ankò.',
      'something_went_wrong_please_try_again': 'Yon bagay te mal pase. Tanpri eseye ankò.',
      'analyzing_image': 'Analize imaj...',
      'processing': 'Tretman...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Efase Medikaman',
      'are_you_sure_delete': 'Eske ou sèten ou vle efase?',
      'cancel': 'Anile',
      'delete': 'Efase',
      'search_medications': 'Rechèch Medikaman',
      'unknown_medication': 'Enkonu, sa a medikaman',
      'brand_name': 'Non Mak',
      'check_info': 'Tcheke enfòmasyon',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Modifye pwofil',
      'language_selection': 'Seleksyon lang',
      'about_us': 'Sou nou',
      'contact_us': 'Kontakte nou',
      'logout': 'Dekonekte',
      'change_photo': 'Chanje foto',
      'full_name': 'Non konplè',
      'error': 'Erè',
      'name_cannot_be_empty': 'Non pa ka vid',
      'success': 'Siksè',
      'profile_updated': 'Pwofil mete ajou avèk siksè',
      'failed_to_update_profile': 'Echwe mete ajou pwofil la',
      'save_changes': 'Sove chanjman yo',
      'english': 'Angle',
      'spanish': 'Panyòl',
      'french': 'Franse',
      'creole': 'Kreyòl',
      'portugese': 'Pòtigè',
      'chinese': 'Chinwa',
      'russian': 'Ris',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Manifakti',
      'drug_class': 'Klas Dwòg',
      'uses': 'Itilizasyon',
      'dosage_information': 'Enfòmasyon sou Dozaj',
      'adults': 'Granmoun',
      'children': 'Timoun',
      'elderly': 'Granmoun Aje',
      'how_to_take': 'Kijan pou Pran',
      'side_effects': 'Efè Segondè',
      'common': 'Komen',
      'serious': 'Grav',
      'warnings': 'Avètisman',
      'storage_instructions': 'Enstriksyon pou Estoke',
      'interactions': 'Entèraksyon',
      'add_notes': 'Ajoute Nòt',
      'save_note': 'Anrejistre Nòt',
      'play': 'Jwe',
      'pause': 'Poz',
      'no_medication_data': 'Pa gen done medikaman',
    },

    'ru': {
      // ============ HOME SCREEN ============
      'hello': 'Здравствуйте',
      'scan_medication': 'Сканировать медикамент',
      'scan_instruction': 'Направьте камеру на этикетку, чтобы определить ваше лекарство.',
      'scan_button': 'Сканировать',
      'recently_scanned': 'Недавнее сканирование',
      'font': 'Open Sans',
      'no_medications_found': 'Медикаменты не найдены',
      'generic_name': 'Общее название',
      'view_details': 'Посмотреть детали',
      'see_all': 'Посмотреть все',

      // ============ BOTTOM NAV ============
      'home': 'Главная',
      'scan': 'Сканировать',
      'medications': 'Лекарства',
      'settings': 'Настройки',

      // ============ SCAN SCREEN ============
      'camera': 'Камера',
      'photos': 'Фотографии',
      'please_select_an_image_first': 'Пожалуйста, сначала выберите изображение',
      'please_login_to_continue': 'Пожалуйста, войдите, чтобы продолжить',
      'uploading_image': 'Загрузка изображения...',
      'ai_is_analyzing_the_image': 'ИИ анализирует изображение...',
      'processing_medication_data': 'Обработка данных о лекарстве...',
      'this_may_take_a_few_seconds': 'Это может занять несколько секунд',
      'please_do_not_close_the_app': 'Пожалуйста, не закрывайте приложение',
      'session_expired_please_login_again': 'Сессия истекла. Пожалуйста, войдите снова.',
      'invalid_image_or_format_not_supported': 'Неверное изображение или неподдерживаемый формат',
      'server_error_please_try_again_later': 'Ошибка сервера. Пожалуйста, попробуйте позже.',
      'no_internet_connection': 'Нет подключения к интернету. Проверьте сеть.',
      'request_timed_out_please_try_again': 'Превышено время ожидания. Попробуйте снова.',
      'something_went_wrong_please_try_again': 'Что-то пошло не так. Попробуйте снова.',
      'analyzing_image': 'Анализ изображения...',
      'processing': 'Обработка...',

      // ============ MEDICATION PAGE ============
      'delete_medication': 'Удалить лекарство',
      'are_you_sure_delete': 'Вы уверены, что хотите удалить?',
      'cancel': 'Отменить',
      'delete': 'Удалить',
      'search_medications': 'Поиск лекарств',
      'unknown_medication': 'Неизвестно, это лекарство',
      'brand_name': 'Марка',
      'check_info': 'Проверить информацию',

      // ============ SETTINGS PAGE ============
      'edit_profile': 'Редактировать профиль',
      'language_selection': 'Выбор языка',
      'about_us': 'О нас',
      'contact_us': 'Свяжитесь с нами',
      'logout': 'Выйти',
      'change_photo': 'Изменить фото',
      'full_name': 'Полное имя',
      'error': 'Ошибка',
      'name_cannot_be_empty': 'Имя не может быть пустым',
      'success': 'Успех',
      'profile_updated': 'Профиль успешно обновлен',
      'failed_to_update_profile': 'Не удалось обновить профиль',
      'save_changes': 'Сохранить изменения',
      'english': 'Английский',
      'spanish': 'Испанский',
      'french': 'Французский',
      'creole': 'Креольский',
      'portugese': 'Португальский',
      'chinese': 'Китайский',
      'russian': 'Русский',

      // ============ MEDICATION DETAILS ============
      'manufacturer': 'Производитель',
      'drug_class': 'Класс Препарата',
      'uses': 'Применение',
      'dosage_information': 'Информация о Дозировке',
      'adults': 'Взрослые',
      'children': 'Дети',
      'elderly': 'Пожилые',
      'how_to_take': 'Как Принимать',
      'side_effects': 'Побочные Эффекты',
      'common': 'Обычные',
      'serious': 'Серьёзные',
      'warnings': 'Предупреждения',
      'storage_instructions': 'Инструкции по Хранению',
      'interactions': 'Взаимодействия',
      'add_notes': 'Добавить Заметки',
      'save_note': 'Сохранить Заметку',
      'play': 'Воспроизвести',
      'pause': 'Пауза',
      'no_medication_data': 'Нет данных о лекарстве',
    },

    'zh_CN': {
      // ============ HOME SCREEN ============
      'hello': '你好',
      'scan_medication': '扫描药物',
      'scan_instruction': '将您的摄像头对准标签以识别药物。',
      'scan_button': '扫描',
      'recently_scanned': '最近扫描',
      'font': 'Open Sans',
      'no_medications_found': '未找到药物',
      'generic_name': '通用名称',
      'view_details': '查看详情',
      'see_all': '查看全部',

      // ============ BOTTOM NAV ============
      'home': '首页',
      'scan': '扫描',
      'medications': '药物',
      'settings': '设置',

      // ============ SCAN SCREEN ============
      'camera': '相机',
      'photos': '照片',
      'please_select_an_image_first': '请先选择一张图片',
      'please_login_to_continue': '请登录以继续',
      'uploading_image': '正在上传图片...',
      'ai_is_analyzing_the_image': 'AI正在分析图片...',
      'processing_medication_data': '正在处理药物数据...',
      'this_may_take_a_few_seconds': '这可能需要几秒钟',
      'please_do_not_close_the_app': '请不要关闭应用程序',
      'session_expired_please_login_again': '会话已过期，请重新登录。',
      'invalid_image_or_format_not_supported': '图片无效或格式不支持',
      'server_error_please_try_again_later': '服务器错误，请稍后重试。',
      'no_internet_connection': '无网络连接，请检查您的网络。',
      'request_timed_out_please_try_again': '请求超时，请重试。',
      'something_went_wrong_please_try_again': '出错了，请重试。',
      'analyzing_image': '分析图片中...',
      'processing': '处理中...',

      // ============ MEDICATION PAGE ============
      'delete_medication': '删除药物',
      'are_you_sure_delete': '您确定要删除吗？',
      'cancel': '取消',
      'delete': '删除',
      'search_medications': '搜索药物',
      'unknown_medication': '未知药物',
      'brand_name': '品牌名称',
      'check_info': '检查信息',

      // ============ SETTINGS PAGE ============
      'edit_profile': '编辑个人资料',
      'language_selection': '语言选择',
      'about_us': '关于我们',
      'contact_us': '联系我们',
      'logout': '退出',
      'change_photo': '更改照片',
      'full_name': '全名',
      'error': '错误',
      'name_cannot_be_empty': '姓名不能为空',
      'success': '成功',
      'profile_updated': '个人资料更新成功',
      'failed_to_update_profile': '更新个人资料失败',
      'save_changes': '保存更改',
      'english': '英语',
      'spanish': '西班牙语',
      'french': '法语',
      'creole': '克里奥尔语',
      'portugese': '葡萄牙语',
      'chinese': '中文',
      'russian': '俄语',

      // ============ MEDICATION DETAILS ============
      'manufacturer': '制造商',
      'drug_class': '药物类别',
      'uses': '用途',
      'dosage_information': '剂量信息',
      'adults': '成人',
      'children': '儿童',
      'elderly': '老年人',
      'how_to_take': '如何服用',
      'side_effects': '副作用',
      'common': '常见',
      'serious': '严重',
      'warnings': '警告',
      'storage_instructions': '存储说明',
      'interactions': '相互作用',
      'add_notes': '添加备注',
      'save_note': '保存备注',
      'play': '播放',
      'pause': '暂停',
      'no_medication_data': '无药物数据',
    },
  };
}
